version: "3.9"
services:
  web_app:
    image: php:8.1.18-apache-bullseye
    ports:
      - "8000:80"
    volumes:
      - "./:/var/www/html/"
  app_db:
    image: mariadb
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: web_app
volumes:
  db_data: {}